### Numpy

- python에서 대규모 다차열 배열을 다룰 수 있게 도와주는 라이브러리.

- numpy는 리스트에 비해서 보다 빠른 연산을 할 수 있다.

### 배열 만들기

In [1]:
# list로 배열 만들기
list(range(10))

# numpy로 배열 만들기
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
# 1차원 배열
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
# 실수형태 배열
# 전부 실수 형태로 들어감
np.array([3,1.4,2,3,4])

array([3. , 1.4, 2. , 3. , 4. ])

In [4]:
# 2차원
np.array([[1,2],
        [3,4]])


array([[1, 2],
       [3, 4]])

In [5]:
# 정수형 배열을 실수형으로 변환
np.array([1,2,3,4],dtype = 'float')

array([1., 2., 3., 4.])

### 배열 데이터 타입 dtype

- 리스트와 다르게 array는 **단일타입**으로 구성된다.


|dtype|설명|다양한 표현|
|-----|-----|----------|
|int|정수형 타입|i,int,int32,int64|
|float|실수형 타입|f,float_,float32,float64|
|str|문자열 타입|str,U,U32|
|bool|부울 타입|?,bool_|

In [6]:
# 실수형으로 데이터가 들어감
arr = np.array([1,2,3,4], dtype = float)
print(arr)
arr.dtype

[1. 2. 3. 4.]


dtype('float64')

In [7]:
# 다시 정수형으로 변환
arr.astype(int)

array([1, 2, 3, 4])

### 다양한 배열 만들기

In [8]:
# 0이 10개인 정수형 배열
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 원소가 1이며 3by5인 실수형 배열 
np.ones((3,5),dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 0부터 20전까지 2개씩 건너뛰는 배열
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# 0부터 1사이에 5개로 나누어진 값의 배열
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 난수로 채워진 배열 만들기

In [12]:
# 데이터가 난수로 채워진 2by2 배열
np.random.random((2,2))

array([[0.65040619, 0.78949692],
       [0.28176491, 0.87174082]])

In [13]:
# 정규분포로 채워진 2by2 배열
np.random.normal(0,1,(2,2))

array([[ 1.14453891, -0.29602406],
       [-1.29180934, -0.07903731]])

In [14]:
# 0부터 10사이에 2by2 배열
np.random.randint(0,10,(2,2))

array([[7, 2],
       [5, 8]])

### 배열의 기초

In [15]:
# 0~10까지의 숫자로 이루어진 3by4 행렬 
x2 = np.random.randint(10,size=(3,4))
x2

array([[4, 2, 1, 6],
       [4, 3, 2, 5],
       [1, 6, 0, 4]])

In [16]:
# 차원 수 확인
x2.ndim

2

In [17]:
# 배열의 모양
x2.shape

(3, 4)

In [18]:
# 원소의 개수
x2.size

12

In [19]:
# 데이터 타입
x2.dtype

dtype('int32')

### 찾고 잘라내기(인덱싱)

In [20]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [21]:
# 4번째 값 가져오기
x[3]

3

In [22]:
# 첫번째값 바꾸기
x[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6])

In [23]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
# 2~4번째 값까지 출력
x[1:4]

array([1, 2, 3])

In [25]:
# 2번째 값부터 끝까지
x[1:]

array([1, 2, 3, 4, 5, 6])

In [26]:
# ~4번째 값까지
x[:4]

array([0, 1, 2, 3])

In [27]:
# 2번째 값씩 건너뛰기
x[::2]

array([0, 2, 4, 6])

### 모양 바꾸기

**reshape** : array의 shape를 변경한다.

In [28]:
x = np.arange(8)
print(x)
x.shape

[0 1 2 3 4 5 6 7]


(8,)

In [29]:
# reshape를 통해 모양을 바꿨다.
x2 = x.reshape((2,4))
print(x2)
x2.shape

[[0 1 2 3]
 [4 5 6 7]]


(2, 4)

### 이어붙이고 나누고
**concate** : array를 이어 붙인다

In [30]:
# 두 배열이 합쳐졌다.
x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [31]:
matrix = np.arange(4).reshape(2,2)
# axis = 0을 줄시 행 아래에 붙는다. 
np.concatenate([matrix,matrix], axis = 0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [32]:
matrix = np.arange(4).reshape(2,2)
# axis = 0을 줄시 열 옆에 붙는다. 
np.concatenate([matrix,matrix], axis = 1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

**np.split**: axis 축을 기준으로 나눌 수 있다.

In [33]:
matrix = np.arange(16).reshape(4,4)
# 행 인덱스 3인 부분을 기준으로 나눈다
# 위에있는 부분은 upper, 아래는 lower
upper,lower = np.split(matrix,[3],axis = 0)
print(upper,lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]]


In [34]:
matrix = np.arange(16).reshape(4,4)
# 열 인덱스 3인 부분을 기준으로 나눈다
# 위에있는 부분은 upper, 아래는 lower
left,right = np.split(matrix,[3],axis = 1)
print(left,right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]] [[ 3]
 [ 7]
 [11]
 [15]]


### numpy 기본연산

In [36]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [37]:
x + 5

array([5, 6, 7, 8])

In [38]:
x - 5

array([-5, -4, -3, -2])

In [39]:
x * 5

array([ 0,  5, 10, 15])

In [40]:
x/5

array([0. , 0.2, 0.4, 0.6])

### 행렬간 연산

In [43]:
x = np.arange(4).reshape((2,2))
y = np.random.randint(10,size = (2,2))
print(x)

print(y)

[[0 1]
 [2 3]]
[[8 7]
 [9 4]]


In [44]:
x + y

array([[ 8,  8],
       [11,  7]])

In [45]:
x - y

array([[-8, -6],
       [-7, -1]])

### 브로드캐스팅(broadcasting)

- shape이 다른 array끼리 연산

In [48]:
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
# 브로드캐스팅
matrix * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [50]:
# 브로드캐스팅2

matrix + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [53]:
x = np.arange(3).reshape((3,1)) 
x

array([[0],
       [1],
       [2]])

In [52]:
y = np.arange(3)
y

array([0, 1, 2])

In [54]:
# 0+(0,1,2) , 1+(0,1,2), 2+(0,1,2)
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [55]:
A = np.arange(6).reshape(3,2)
B = np.arange(3).reshape(3,1)
print(A+B)

[[0 1]
 [3 4]
 [6 7]]


### 집계함수

- 집계 : 데이터에 대한 요약 통계를 볼 수 있다.

In [57]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
# 원소의 합
np.sum(x)

28

In [59]:
# 원소 최솟값
np.min(x)

0

In [60]:
# 원소 최댓값
np.max(x)

7

In [61]:
# 원소 평균값
np.mean(x)

3.5

In [62]:
# 원소 표준편차
np.std(x)

2.29128784747792

In [63]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
# 열을 기준으로 sum
np.sum(x,axis = 0)

array([ 4,  6,  8, 10])

In [65]:
# 행을 기준으로 sum
np.sum(x,axis = 1)

array([ 6, 22])

### 마스킹 연산

- **true,false array**를 통해서 특정 값들을 뽑아내는 방법

In [67]:
x = np.arange(5)

x

array([0, 1, 2, 3, 4])

In [68]:
x < 3

array([ True,  True,  True, False, False])

In [69]:
x > 5

array([False, False, False, False, False])

In [70]:
# true인 값들만 뽑아냄
x[x<3]

array([0, 1, 2])

In [78]:
import numpy as np

daily_liar_data = [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]


# 양치기 소년이 거짓말을 몇 번 했는지 구하여 출력해주세요.

def main() :
    liar_array = np.array(daily_liar_data)
    print(len(liar_array[liar_array == 0]))
    

In [77]:
def main() :
    liar_array = np.array(daily_liar_data)
    print(np.count_nonzero(liar_array == 0))