### 스칼라와 벡터

- 스칼라 : 길이, 넓이, 질량, 온도<br>
크기만 존재하는 양


- 벡터 : 속도, 위치 이동, 힘<br>
크기와 방향이 모두 존재하는 양

### 행렬 만들기

In [1]:
import numpy as np

A = np.array([[1,2],
             [3,4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
print(A*3)

[[ 3  6]
 [ 9 12]]


In [4]:
print(A+A)

[[2 4]
 [6 8]]


In [5]:
print(A**2)

[[ 1  4]
 [ 9 16]]


In [6]:
print(3 ** A)

[[ 3  9]
 [27 81]]


In [7]:
print(A ** A)

[[  1   4]
 [ 27 256]]


In [8]:
x = np.array([[1,2],
              [3,4]])

y= np.array([[4,5],
            [5,6]])

print(x,y)

[[1 2]
 [3 4]] [[4 5]
 [5 6]]


In [9]:
# 행렬의 곱
print(np.dot(x,y))

[[14 17]
 [32 39]]


In [10]:
# dot과 다른 결과
print(x*y)

[[ 4 10]
 [15 24]]


In [11]:
# 비교 연산 

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [12]:
print(a == b)
print(a > b)

[False False False False]
[False False False False]


In [13]:
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)

In [14]:
np.logical_or(a,b)
np.logical_and(a,b)

array([ True, False, False, False])

### transpose

- 전치행렬은 원행렬의 행과 열을 뒤바꾼 행렬이다.

In [2]:
A = np.array([[1,2,-1],[4,3,0]])
A

array([[ 1,  2, -1],
       [ 4,  3,  0]])

In [3]:
# 전치
A.transpose()

array([[ 1,  4],
       [ 2,  3],
       [-1,  0]])

In [4]:
# 행렬만들기
a = np.array([[1,2],[3,4]])

In [5]:
# a**2 = aa이나 넘파이에서는 같은 위치에 있는 것들을 제곱함.
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [9]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[3,2]])

print(x)
print(y)

[[1 2]
 [3 4]]
[[3 4]
 [3 2]]


In [7]:
# 곱이 다르다.
print(np.dot(x,y))
print(x*y)

[[ 9  8]
 [21 20]]
[[3 8]
 [9 8]]


In [10]:
# 비교연산

a = np.array([1,2,3,4])
b = np.array([2,2,2,2])

In [12]:
print(a == b)
print(a > b)

[False  True False False]
[False False  True  True]


In [16]:
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)

print(a)
print(b)

[ True  True False False]
[ True False  True False]


In [15]:
# or : 둘중 하나라도 true일 경우 true
# and : 둘다 true일 경우 true
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


In [18]:
a = np.array([1,2,3,4,5])

argmin/max : 최소/최대값의 인덱스를 반환

In [19]:
# a의 합
print(np.sum(a))
print(a.sum())

# a의 최솟값과 최댓값
print(a.min())
print(a.max())

# 1의 인덱스값과 5의 인덱스값을 리턴
print(a.argmin())
print(a.argmax())

15
15
1
5
0
4


In [20]:
a = np.array([1,1,1],dtype = bool)
b = np.array([1,1,0], dtype = bool)

print(a)
print(b)

[ True  True  True]
[ True  True False]


In [22]:
# 모든값이 true인지?
print(np.all(a))
print(np.all(b))

# 하나라도 true인지?
print(np.any(a))
print(np.all(a))

True
False
True
True


In [23]:
x = np.array([1,2,3,1])

In [24]:
print(np.mean(x))
print(np.median(x))
print(np.std(x))

1.75
1.5
0.82915619758885


In [33]:
import numpy as np

def main():
    A = get_matrix()
    print(matrix_tutorial(A))

def get_matrix():
    mat = []
    
    # string 이므로 나눠줘야함
    first_row = input()
    n = int(first_row.split(' ')[0])
    m = int(first_row.split(' ')[1])
    for i in range(n) :
        row = input()
        # input으로 넣은 row를 공백으로 분리해서 int로 변환해라.
        mat.append([int(x) for x in row.split(' ')])
    return np.array(mat)

def matrix_tutorial(A) :
    B = A.T
    print(B)
    
    try :
        C = np.linalg.inv(B)
    except : 
        return "not invertible"
    return (np.sum(C > 0))
    return 0

if __name__ == "__main__":
    main()


    3 5     1 2 6 3 8     11 0 -1 3 1     9 0 7 -3 4


ValueError: invalid literal for int() with base 10: ''