### 스칼라와 벡터

- 스칼라 : 길이, 넓이, 질량, 온도<br>
크기만 존재하는 양


- 벡터 : 속도, 위치 이동, 힘<br>
크기와 방향이 모두 존재하는 양

### 행렬 만들기

In [2]:
import numpy as np

A = np.array([[1,2],
             [3,4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
print(A*3)

[[ 3  6]
 [ 9 12]]


In [4]:
print(A+A)

[[2 4]
 [6 8]]


In [5]:
print(A**2)

[[ 1  4]
 [ 9 16]]


In [6]:
print(3 ** A)

[[ 3  9]
 [27 81]]


In [7]:
print(A ** A)

[[  1   4]
 [ 27 256]]


In [8]:
x = np.array([[1,2],
              [3,4]])

y= np.array([[4,5],
            [5,6]])

print(x,y)

[[1 2]
 [3 4]] [[4 5]
 [5 6]]


In [9]:
# 행렬의 곱
print(np.dot(x,y))

[[14 17]
 [32 39]]


In [10]:
# dot과 다른 결과
print(x*y)

[[ 4 10]
 [15 24]]


In [11]:
# 비교 연산 

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [12]:
print(a == b)
print(a > b)

[False False False False]
[False False False False]


In [13]:
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)

In [14]:
np.logical_or(a,b)
np.logical_and(a,b)

array([ True, False, False, False])